title: PCjs Machines
domain: luihum.github.io/pcjs/
tagline: Home of the original IBM PC emulator for browsers.
description: >
  PCjs offers a variety of online machine emulators written in JavaScript. Run DOS, Windows, OS/2 and other vintage PC
  applications in a web browser on your desktop computer, iPhone, or iPad. An assortment of microcomputers, minicomputers, terminals,
  programmable calculators, and arcade machines are available, along with an archive of historical software and documentation.
author: Jeff Parsons
logo: /assets/img/logo-home.png
data_dir: configs
left_brace: "{"
right_brace: "}" 
encoding: UTF-8

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - README.md
  - TODO.md
  - "*.log"
  - tmp
  - "**/archive"
  - "**/private"
  - /package*.json
  - /.history
  - /.vscode
  - /discs
  - /diskettes
  - /gamedisks
  - /harddisks
  - /private
  - /node_modules
  - /software/pcx86/sys/dos/microsoft/1.25/src
  - /software/pcx86/sys/dos/microsoft/2.11/src

github:
  name_of_the_guy_who_technically_owns_this_repo: "luihum"
  original_author_name: "jeffpar"
  original_author_url: https://github.com/jeffpar
  url_of_the_guy_who_technically_owns_this_repo: https://github.com/luihum
  repository_url: https://github.com/luihum/pcjs
  pages: https://github.com/luihum/pcjs/tree/gh-pages

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
#   disable: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache

software:
  diskettes:
    server: https://diskettes.pcjs.org
  gamedisks:
    server: https://gamedisks.pcjs.org
  harddisks:
    server: https://harddisks.pcjs.org
 
archive:
  ms:
    server: https://msarchive.pcjs.org
  kb:
    server: https://jeffpar.github.io/kbarchive

theme: jekyll-theme-minimal
